// @ts-check
/**
 * TS 类型 codegen
 *
 * - openapi/*.yaml  → dist/ts/<name>.d.ts(用 openapi-typescript)
 * - ws/*.schema.json + live-context/*.schema.json
 *                  → dist/ts/<name>.d.ts(用 json-schema-to-typescript)
 * - dist/ts/index.d.ts/.js 汇总 re-export
 *
 * 设计原则:
 *  - 不依赖网络;依赖通过 pnpm i 安装到 packages/proto/node_modules
 *  - 任意输入文件不存在,跳过且不致命(允许阶段性产出)
 *  - 失败仅打印,不中断其它生成,最终以 exit code 反映整体
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "dist", "ts");

const SOURCES = {
  openapi: [
    { file: "openapi/visitor.yaml", out: "visitor.d.ts", export: "visitor" },
    { file: "openapi/agent.yaml", out: "agent.d.ts", export: "agent", optional: true },
    { file: "openapi/admin.yaml", out: "admin.d.ts", export: "admin", optional: true },
    { file: "openapi/ai-internal.yaml", out: "ai-internal.d.ts", export: "ai", optional: true },
    { file: "openapi/tool.yaml", out: "tool.d.ts", export: "tool", optional: true },
  ],
  jsonSchema: [
    { file: "ws/client.schema.json", out: "ws-client.d.ts", export: "WsClient", typeName: "WsClientFrame" },
    { file: "ws/events.schema.json", out: "ws-events.d.ts", export: "WsEvents", typeName: "WsServerEvent" },
    {
      file: "live-context/live-context.schema.json",
      out: "live-context.d.ts",
      export: "LiveContext",
      typeName: "LiveContext",
    },
  ],
};

let anyFailure = false;

async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

async function exists(p) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function loadModuleOrFail(spec, hint) {
  try {
    return await import(spec);
  } catch (err) {
    console.error(`[codegen-ts] 缺少依赖 ${spec}。${hint}`);
    console.error(`            请在仓库根执行: pnpm i`);
    console.error(`            原始错误: ${(err && err.message) || err}`);
    return null;
  }
}

async function genOpenApi() {
  /** @type {any} */
  const mod = await loadModuleOrFail(
    "openapi-typescript",
    "(openapi/*.yaml → .d.ts 由它生成)",
  );
  if (!mod) {
    anyFailure = true;
    return;
  }
  const openapiTS = mod.default ?? mod.openapiTS ?? mod;

  for (const item of SOURCES.openapi) {
    const abs = path.join(ROOT, item.file);
    if (!(await exists(abs))) {
      if (!item.optional) {
        console.warn(`[codegen-ts] 必填源不存在: ${item.file}`);
      }
      continue;
    }
    try {
      const out = await openapiTS(pathToFileURL(abs).href);
      const target = path.join(OUT, item.out);
      const txt = typeof out === "string" ? out : String(out);
      const banner =
        `/* eslint-disable */\n` +
        `// AUTOGENERATED — DO NOT EDIT。来源: packages/proto/${item.file}\n\n`;
      await fs.writeFile(target, banner + txt + "\n");
      console.log(`[codegen-ts] OK  ${item.file} → dist/ts/${item.out}`);
    } catch (err) {
      anyFailure = true;
      console.error(`[codegen-ts] FAIL ${item.file}: ${(err && err.message) || err}`);
    }
  }
}

async function genJsonSchema() {
  /** @type {any} */
  const mod = await loadModuleOrFail(
    "json-schema-to-typescript",
    "(ws/*.schema.json + live-context 由它生成 .d.ts)",
  );
  if (!mod) {
    anyFailure = true;
    return;
  }
  const compileFromFile = mod.compileFromFile ?? mod.default?.compileFromFile;

  for (const item of SOURCES.jsonSchema) {
    const abs = path.join(ROOT, item.file);
    if (!(await exists(abs))) {
      console.warn(`[codegen-ts] 源不存在: ${item.file}`);
      continue;
    }
    try {
      const ts = await compileFromFile(abs, {
        cwd: path.dirname(abs),
        bannerComment: `/* eslint-disable */\n// AUTOGENERATED — DO NOT EDIT。来源: packages/proto/${item.file}`,
        unreachableDefinitions: true,
        additionalProperties: false,
      });
      const target = path.join(OUT, item.out);
      await fs.writeFile(target, ts);
      console.log(`[codegen-ts] OK  ${item.file} → dist/ts/${item.out}`);
    } catch (err) {
      anyFailure = true;
      console.error(`[codegen-ts] FAIL ${item.file}: ${(err && err.message) || err}`);
    }
  }
}

async function writeIndex() {
  const lines = [
    `/* AUTOGENERATED — DO NOT EDIT */`,
    `// 由 packages/proto/scripts/codegen-ts.mjs 输出`,
    ``,
  ];
  const declLines = [`/* AUTOGENERATED — DO NOT EDIT */`, ``];

  for (const item of [...SOURCES.openapi, ...SOURCES.jsonSchema]) {
    const file = path.join(OUT, item.out);
    if (!(await exists(file))) continue;
    const baseNoExt = item.out.replace(/\.d\.ts$/, "");
    declLines.push(
      `export * as ${item.export} from "./${baseNoExt}.js";`,
    );
  }

  await fs.writeFile(path.join(OUT, "index.js"), lines.join("\n"));
  await fs.writeFile(path.join(OUT, "index.d.ts"), declLines.join("\n") + "\n");
  console.log(`[codegen-ts] index.{js,d.ts} 写入完成`);
}

async function main() {
  await ensureDir(OUT);
  await genOpenApi();
  await genJsonSchema();
  await writeIndex();
  if (anyFailure) {
    console.error("[codegen-ts] 存在失败项");
    process.exit(1);
  }
  console.log("[codegen-ts] 完成");
}

main().catch((err) => {
  console.error("[codegen-ts] 顶层异常:", err);
  process.exit(1);
});
