// @ts-check
/**
 * Python pydantic models codegen — 通过 datamodel-code-generator (Python 工具)。
 *
 * - openapi/*.yaml → dist/python/<name>.py
 * - live-context.schema.json → dist/python/live_context.py
 *
 * 调用方式: 优先 `uv run datamodel-codegen`,缺失则尝试 `python -m datamodel_code_generator`。
 * 没有 Python 环境时,仅打印警告,不阻塞 TS 生成或 CI 构建。
 */

import { spawnSync } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "dist", "python");

const SOURCES = [
  { file: "openapi/visitor.yaml", out: "visitor.py", inputType: "openapi" },
  { file: "openapi/agent.yaml", out: "agent.py", inputType: "openapi", optional: true },
  { file: "openapi/admin.yaml", out: "admin.py", inputType: "openapi", optional: true },
  { file: "openapi/ai-internal.yaml", out: "ai_internal.py", inputType: "openapi", optional: true },
  { file: "openapi/tool.yaml", out: "tool.py", inputType: "openapi", optional: true },
  {
    file: "live-context/live-context.schema.json",
    out: "live_context.py",
    inputType: "jsonschema",
  },
  { file: "ws/client.schema.json", out: "ws_client.py", inputType: "jsonschema" },
  { file: "ws/events.schema.json", out: "ws_events.py", inputType: "jsonschema" },
];

function detectRunner() {
  const candidates = [
    { cmd: "uv", args: ["run", "--quiet", "datamodel-codegen"] },
    { cmd: "datamodel-codegen", args: [] },
    { cmd: "python", args: ["-m", "datamodel_code_generator"] },
    { cmd: "python3", args: ["-m", "datamodel_code_generator"] },
  ];
  for (const c of candidates) {
    const r = spawnSync(c.cmd, [...c.args, "--version"], { stdio: "ignore" });
    if (r.status === 0) return c;
  }
  return null;
}

async function exists(p) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  const runner = detectRunner();
  if (!runner) {
    console.warn(
      "[codegen-py] 跳过:未找到 datamodel-code-generator(请 `uv add --group dev datamodel-code-generator` 或 `pipx install datamodel-code-generator`)",
    );
    return;
  }
  await fs.mkdir(OUT, { recursive: true });

  let anyFailure = false;
  for (const item of SOURCES) {
    const abs = path.join(ROOT, item.file);
    if (!(await exists(abs))) {
      if (!item.optional) console.warn(`[codegen-py] 源不存在: ${item.file}`);
      continue;
    }
    const target = path.join(OUT, item.out);
    const args = [
      ...runner.args,
      "--input",
      abs,
      "--input-file-type",
      item.inputType,
      "--output",
      target,
      "--output-model-type",
      "pydantic_v2.BaseModel",
      "--target-python-version",
      "3.11",
      "--use-schema-description",
      "--use-field-description",
      "--use-default-kwarg",
      "--collapse-root-models",
      "--field-constraints",
    ];
    const res = spawnSync(runner.cmd, args, { stdio: "inherit" });
    if (res.status !== 0) {
      anyFailure = true;
      console.error(`[codegen-py] FAIL ${item.file}`);
    } else {
      console.log(`[codegen-py] OK  ${item.file} → dist/python/${item.out}`);
    }
  }

  // __init__.py
  const initLines = ['"""AUTOGENERATED — DO NOT EDIT"""', ""];
  await fs.writeFile(path.join(OUT, "__init__.py"), initLines.join("\n"));

  if (anyFailure) {
    console.error("[codegen-py] 存在失败项");
    process.exit(1);
  }
  console.log("[codegen-py] 完成");
}

main().catch((err) => {
  console.error("[codegen-py] 顶层异常:", err);
  process.exit(1);
});
